// Code generated by protoc-gen-go. DO NOT EDIT.
// source: site.proto

package site

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71f40f4d1c91b943, []int{0}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ShowReply struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SecondTitle          string   `protobuf:"bytes,3,opt,name=secondTitle,proto3" json:"secondTitle,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Icp                  string   `protobuf:"bytes,5,opt,name=icp,proto3" json:"icp,omitempty"`
	LogoUrl              string   `protobuf:"bytes,6,opt,name=logoUrl,proto3" json:"logoUrl,omitempty"`
	Owner                string   `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	CreateTime           string   `protobuf:"bytes,10,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           string   `protobuf:"bytes,11,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReply) Reset()         { *m = ShowReply{} }
func (m *ShowReply) String() string { return proto.CompactTextString(m) }
func (*ShowReply) ProtoMessage()    {}
func (*ShowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_71f40f4d1c91b943, []int{1}
}

func (m *ShowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply.Unmarshal(m, b)
}
func (m *ShowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply.Marshal(b, m, deterministic)
}
func (m *ShowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply.Merge(m, src)
}
func (m *ShowReply) XXX_Size() int {
	return xxx_messageInfo_ShowReply.Size(m)
}
func (m *ShowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply proto.InternalMessageInfo

func (m *ShowReply) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ShowReply) GetSecondTitle() string {
	if m != nil {
		return m.SecondTitle
	}
	return ""
}

func (m *ShowReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ShowReply) GetIcp() string {
	if m != nil {
		return m.Icp
	}
	return ""
}

func (m *ShowReply) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *ShowReply) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ShowReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ShowReply) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ShowReply) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *ShowReply) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*ShowRequest)(nil), "site.showRequest")
	proto.RegisterType((*ShowReply)(nil), "site.showReply")
}

func init() { proto.RegisterFile("site.proto", fileDescriptor_71f40f4d1c91b943) }

var fileDescriptor_71f40f4d1c91b943 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0x9a, 0xb4, 0x66, 0x02, 0xfe, 0x59, 0x3c, 0x2c, 0x1e, 0x24, 0xe4, 0xd4, 0x83,
	0x54, 0x50, 0x9f, 0x24, 0xad, 0x0f, 0x50, 0x93, 0xc1, 0x0c, 0x6c, 0x33, 0x6b, 0xb2, 0x21, 0xf4,
	0x39, 0x7c, 0x61, 0xd9, 0x59, 0xa3, 0x01, 0x6f, 0xf3, 0xfd, 0x7e, 0x3b, 0x7c, 0x30, 0x0b, 0x30,
	0x90, 0xc3, 0x9d, 0xed, 0xd9, 0xb1, 0x4a, 0xfc, 0x5c, 0x3e, 0x41, 0x3e, 0xb4, 0x3c, 0x55, 0xf8,
	0x39, 0xe2, 0xe0, 0xd4, 0x15, 0xc4, 0xd4, 0xe8, 0xa8, 0x88, 0xb6, 0x69, 0x15, 0x53, 0xa3, 0x6e,
	0x60, 0x35, 0xf6, 0x46, 0xc7, 0x45, 0xb4, 0xcd, 0x2a, 0x3f, 0x96, 0x5f, 0x31, 0x64, 0x61, 0xc3,
	0x9a, 0xf3, 0xbf, 0xf7, 0x77, 0x90, 0x3a, 0x72, 0x06, 0x7f, 0x36, 0x42, 0x50, 0x05, 0xe4, 0x03,
	0xd6, 0xdc, 0x35, 0x07, 0x71, 0x2b, 0x71, 0x4b, 0x34, 0xf7, 0x24, 0xbf, 0x3d, 0x9e, 0x50, 0x6d,
	0x75, 0x1a, 0x08, 0xd5, 0x56, 0x69, 0xd8, 0x18, 0xfe, 0xe0, 0xb7, 0xde, 0xe8, 0xb5, 0xd0, 0x39,
	0xfa, 0x56, 0x9e, 0x3a, 0xec, 0xf5, 0x26, 0xb4, 0x4a, 0xf0, 0x14, 0x4f, 0x47, 0x32, 0xfa, 0x32,
	0x50, 0x09, 0x9e, 0xda, 0x96, 0x3b, 0xd4, 0x59, 0xa0, 0x12, 0xd4, 0x03, 0x40, 0xdd, 0xe3, 0xd1,
	0xe1, 0x81, 0x4e, 0xa8, 0x41, 0xd4, 0x82, 0x78, 0x3f, 0xda, 0x66, 0xf6, 0x79, 0xf0, 0x7f, 0xe4,
	0xf9, 0x15, 0x92, 0x3d, 0x39, 0x54, 0x8f, 0x90, 0xec, 0x5b, 0x9e, 0xd4, 0xed, 0x4e, 0x2e, 0xbd,
	0x38, 0xed, 0xfd, 0xf5, 0x12, 0x59, 0x73, 0x2e, 0x2f, 0xde, 0xd7, 0xf2, 0x13, 0x2f, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0xf5, 0xf2, 0xc8, 0x97, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SiteClient is the client API for Site service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SiteClient interface {
	Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error)
}

type siteClient struct {
	cc *grpc.ClientConn
}

func NewSiteClient(cc *grpc.ClientConn) SiteClient {
	return &siteClient{cc}
}

func (c *siteClient) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error) {
	out := new(ShowReply)
	err := c.cc.Invoke(ctx, "/site.Site/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SiteServer is the server API for Site service.
type SiteServer interface {
	Show(context.Context, *ShowRequest) (*ShowReply, error)
}

func RegisterSiteServer(s *grpc.Server, srv SiteServer) {
	s.RegisterService(&_Site_serviceDesc, srv)
}

func _Site_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SiteServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/site.Site/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SiteServer).Show(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Site_serviceDesc = grpc.ServiceDesc{
	ServiceName: "site.Site",
	HandlerType: (*SiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Show",
			Handler:    _Site_Show_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "site.proto",
}
