// Code generated by protoc-gen-go. DO NOT EDIT.
// source: template.proto

package template

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type ShowRequest struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{0}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

// The response message containing the greetings
type ShowReply struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReply) Reset()         { *m = ShowReply{} }
func (m *ShowReply) String() string { return proto.CompactTextString(m) }
func (*ShowReply) ProtoMessage()    {}
func (*ShowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1b68e1b5f001c74, []int{1}
}

func (m *ShowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply.Unmarshal(m, b)
}
func (m *ShowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply.Marshal(b, m, deterministic)
}
func (m *ShowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply.Merge(m, src)
}
func (m *ShowReply) XXX_Size() int {
	return xxx_messageInfo_ShowReply.Size(m)
}
func (m *ShowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply proto.InternalMessageInfo

func (m *ShowReply) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func init() {
	proto.RegisterType((*ShowRequest)(nil), "template.ShowRequest")
	proto.RegisterType((*ShowReply)(nil), "template.ShowReply")
}

func init() { proto.RegisterFile("template.proto", fileDescriptor_b1b68e1b5f001c74) }

var fileDescriptor_b1b68e1b5f001c74 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x49, 0xcd, 0x2d,
	0xc8, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x74,
	0xb9, 0xb8, 0x83, 0x33, 0xf2, 0xcb, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xe4, 0xb8,
	0xb8, 0x60, 0x52, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x48, 0x22, 0x4a, 0xda,
	0x5c, 0x9c, 0x10, 0xe5, 0x05, 0x39, 0x95, 0x84, 0x14, 0x1b, 0xd9, 0x73, 0x71, 0x84, 0x40, 0x79,
	0x42, 0xc6, 0x5c, 0xcc, 0xee, 0xa9, 0x25, 0x42, 0xa2, 0x7a, 0x70, 0x97, 0x20, 0x59, 0x2b, 0x25,
	0x8c, 0x2e, 0x5c, 0x90, 0x53, 0xa9, 0xc4, 0x90, 0xc4, 0x06, 0x76, 0xad, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0x91, 0x4a, 0x35, 0x7d, 0xbf, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateClient interface {
	//   show
	Get(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error)
}

type templateClient struct {
	cc *grpc.ClientConn
}

func NewTemplateClient(cc *grpc.ClientConn) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) Get(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error) {
	out := new(ShowReply)
	err := c.cc.Invoke(ctx, "/template.Template/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
type TemplateServer interface {
	//   show
	Get(context.Context, *ShowRequest) (*ShowReply, error)
}

// UnimplementedTemplateServer can be embedded to have forward compatible implementations.
type UnimplementedTemplateServer struct {
}

func (*UnimplementedTemplateServer) Get(ctx context.Context, req *ShowRequest) (*ShowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterTemplateServer(s *grpc.Server, srv TemplateServer) {
	s.RegisterService(&_Template_serviceDesc, srv)
}

func _Template_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Template/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Get(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Template_serviceDesc = grpc.ServiceDesc{
	ServiceName: "template.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Template_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "template.proto",
}
