[log]
    dir = "/data/log/bbq"

[bm]
    addr = "0.0.0.0:8803"
    timeout = "1s"


[mysql]
    dns= "root:@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local"
    logMode = true
    maxIdleConns = 10
    OpenConns = 100

[redis]
    maxActive = 10
    idleTimeOut = 2
    wait = false
    host = "127.0.0.1:6379"
    password = ""
    db = 1
    conTimeOut = 1
    readTimeOut = 2
    writeTimeOut = 2