[mysql]
    dns= "debian-sys-maint:LHTOotjuBqBQmtT5@(127.0.0.1:3306)/makaplatv4?charset=utf8&parseTime=True&loc=Local"
    logMode = true
    maxIdleConns = 10
    OpenConns = 100

[redis]
    maxActive = 10
    MaxIdle = 10
    idleTimeOut = 2
    wait = false
    host = "127.0.0.1:6379"
    password = ""
    db = 1
    conTimeOut = 1
    readTimeOut = 2
    writeTimeOut = 2
[etcd]
    ETCDEndpoints = ["127.0.0.1:2379"]

[server]
    host="127.0.0.1"
    port="9001"
    addr="127.0.0.1:9001"
    ttl=15