// Code generated by protoc-gen-go. DO NOT EDIT.
// source: templateStore.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShowReplyStatus int32

const (
	ShowReply_REVIEWING ShowReplyStatus = 0
)

var ShowReplyStatus_name = map[int32]string{
	0: "REVIEWING",
}

var ShowReplyStatus_value = map[string]int32{
	"REVIEWING": 0,
}

func (x ShowReplyStatus) String() string {
	return proto.EnumName(ShowReplyStatus_name, int32(x))
}

func (ShowReplyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3d47e821c79faf9f, []int{1, 0}
}

// The request message containing the user's name.
type ShowRequest struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d47e821c79faf9f, []int{0}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

// The response message containing the greetings
type ShowReply struct {
	TemplateId           string   `protobuf:"bytes,1,opt,name=templateId,proto3" json:"templateId,omitempty"`
	DesignerId           int32    `protobuf:"varint,2,opt,name=designerId,proto3" json:"designerId,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Version              int32    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Star                 int32    `protobuf:"varint,5,opt,name=star,proto3" json:"star,omitempty"`
	Level                int32    `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Sort                 int32    `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	IsVipFree            int32    `protobuf:"varint,9,opt,name=isVipFree,proto3" json:"isVipFree,omitempty"`
	TemplateInfo         string   `protobuf:"bytes,10,opt,name=templateInfo,proto3" json:"templateInfo,omitempty"`
	TemplateProperty     string   `protobuf:"bytes,11,opt,name=templateProperty,proto3" json:"templateProperty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReply) Reset()         { *m = ShowReply{} }
func (m *ShowReply) String() string { return proto.CompactTextString(m) }
func (*ShowReply) ProtoMessage()    {}
func (*ShowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d47e821c79faf9f, []int{1}
}

func (m *ShowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReply.Unmarshal(m, b)
}
func (m *ShowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReply.Marshal(b, m, deterministic)
}
func (m *ShowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReply.Merge(m, src)
}
func (m *ShowReply) XXX_Size() int {
	return xxx_messageInfo_ShowReply.Size(m)
}
func (m *ShowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReply proto.InternalMessageInfo

func (m *ShowReply) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *ShowReply) GetDesignerId() int32 {
	if m != nil {
		return m.DesignerId
	}
	return 0
}

func (m *ShowReply) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ShowReply) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ShowReply) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *ShowReply) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ShowReply) GetSort() int32 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ShowReply) GetIsVipFree() int32 {
	if m != nil {
		return m.IsVipFree
	}
	return 0
}

func (m *ShowReply) GetTemplateInfo() string {
	if m != nil {
		return m.TemplateInfo
	}
	return ""
}

func (m *ShowReply) GetTemplateProperty() string {
	if m != nil {
		return m.TemplateProperty
	}
	return ""
}

func init() {
	proto.RegisterEnum("templateStore.ShowReplyStatus", ShowReplyStatus_name, ShowReplyStatus_value)
	proto.RegisterType((*ShowRequest)(nil), "templateStore.ShowRequest")
	proto.RegisterType((*ShowReply)(nil), "templateStore.ShowReply")
}

func init() { proto.RegisterFile("templateStore.proto", fileDescriptor_3d47e821c79faf9f) }

var fileDescriptor_3d47e821c79faf9f = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xfb, 0x37, 0x25, 0xd3, 0x37, 0x50, 0xe6, 0x15, 0x1c, 0x8a, 0x48, 0xc9, 0xa9, 0x08,
	0xf6, 0xa0, 0x67, 0x8f, 0xb5, 0xe4, 0x52, 0x24, 0x95, 0x7a, 0x8e, 0x66, 0xd4, 0x40, 0xcc, 0xae,
	0xbb, 0xd3, 0x4a, 0xbe, 0x9d, 0x1f, 0x4d, 0xba, 0x31, 0x9a, 0xa0, 0xe0, 0x2d, 0xcf, 0xef, 0xf9,
	0x31, 0x64, 0x79, 0xe0, 0xbf, 0xf0, 0x8b, 0xce, 0x13, 0xe1, 0x8d, 0x28, 0xc3, 0x0b, 0x6d, 0x94,
	0x28, 0x0c, 0x5a, 0x30, 0x3c, 0x87, 0xf1, 0xe6, 0x59, 0xbd, 0xc5, 0xfc, 0xba, 0x63, 0x2b, 0x78,
	0x0a, 0x50, 0xf7, 0x51, 0x4a, 0xdd, 0x59, 0x77, 0xee, 0xc7, 0x0d, 0x12, 0xbe, 0xf7, 0xc0, 0xaf,
	0x7c, 0x9d, 0x97, 0x7f, 0xd9, 0x87, 0x3e, 0x65, 0x9b, 0x3d, 0x15, 0x6c, 0xa2, 0x94, 0x7a, 0xb3,
	0xee, 0x7c, 0x18, 0x37, 0x08, 0x1e, 0xc1, 0x50, 0x9b, 0xec, 0x81, 0xa9, 0xef, 0xaa, 0x2a, 0x20,
	0xc1, 0x68, 0xcf, 0xc6, 0x66, 0xaa, 0xa0, 0x81, 0xe3, 0x75, 0x44, 0x84, 0x81, 0x95, 0xc4, 0xd0,
	0xd0, 0x61, 0xf7, 0x7d, 0xb8, 0x91, 0xf3, 0x9e, 0x73, 0xf2, 0xaa, 0x1b, 0x2e, 0x38, 0x53, 0x19,
	0xa1, 0xd1, 0xa7, 0xa9, 0x8c, 0xe0, 0x09, 0xf8, 0x99, 0xdd, 0x66, 0xfa, 0xda, 0x30, 0x93, 0xef,
	0x8a, 0x6f, 0x80, 0x21, 0xfc, 0xfb, 0xfa, 0xf3, 0xe2, 0x51, 0x11, 0xb8, 0xd7, 0xb4, 0x18, 0x9e,
	0xc1, 0xa4, 0xce, 0x37, 0x46, 0x69, 0x36, 0x52, 0xd2, 0xd8, 0x79, 0x3f, 0x78, 0x78, 0x0c, 0x9e,
	0x95, 0x44, 0x76, 0x16, 0x03, 0xf0, 0xe3, 0xe5, 0x36, 0x5a, 0xde, 0x45, 0xeb, 0xd5, 0xa4, 0x73,
	0xb1, 0x86, 0xe0, 0xb6, 0x39, 0x01, 0x5e, 0x41, 0x7f, 0xc5, 0x82, 0xd3, 0x45, 0x7b, 0xae, 0xc6,
	0x2c, 0x53, 0xfa, 0xb5, 0xd3, 0x79, 0x19, 0x76, 0xee, 0x3d, 0xb7, 0xeb, 0xe5, 0x47, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x4d, 0xe0, 0x8c, 0x6e, 0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TemplateStoreClient is the client API for TemplateStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TemplateStoreClient interface {
	//   show
	Get(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error)
}

type templateStoreClient struct {
	cc *grpc.ClientConn
}

func NewTemplateStoreClient(cc *grpc.ClientConn) TemplateStoreClient {
	return &templateStoreClient{cc}
}

func (c *templateStoreClient) Get(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowReply, error) {
	out := new(ShowReply)
	err := c.cc.Invoke(ctx, "/templateStore.TemplateStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateStoreServer is the server API for TemplateStore service.
type TemplateStoreServer interface {
	//   show
	Get(context.Context, *ShowRequest) (*ShowReply, error)
}

func RegisterTemplateStoreServer(s *grpc.Server, srv TemplateStoreServer) {
	s.RegisterService(&_TemplateStore_serviceDesc, srv)
}

func _TemplateStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templateStore.TemplateStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateStoreServer).Get(ctx, req.(*ShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TemplateStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "templateStore.TemplateStore",
	HandlerType: (*TemplateStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _TemplateStore_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "templateStore.proto",
}
